### ISSUE TITLE
Principle

### ISSUE THREAD

**Issue by hyq123-cmd** [floriandotpy/20bn-realtimenet#2]
I really want to know the principle of net, especially the (It’s not about the part of neural network). Can you tell me where  I can  know about it ?

**Comment by floriandotpy** [comment]
Hi @hyq123-cmd 

This repository is a fork of https://github.com/TwentyBN/sense

Can you ask your question over there, please?

**Comment by hyq123-cmd** [comment]
oh! sure, thank you very much.
